### ISSUE TITLE
NullReferenceException when opening files

### ISSUE THREAD

**Issue by ite-klass** [emartineau/SelectionWrapper#3] opened 2019-11-08 10:02 UTC
Multiple times now I have opened/switched files and VS reports exceptions. Checking the activity log its NullReferenceExceptions from this plugin.

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at SelectionWrapper.Wrapper.Wrap(ITextBuffer textBuffer)
   at SelectionWrapper.EditorListener.TextBuffer_PostChanged(Object sender, EventArgs e)
   at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.RaiseEvent(Object sender, EventHandler eventHandlers)
 --- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
--
```

Just now I opened a file with CTRL+T, typing part of the file name, and hitting enter.

I can not directly reproduce it though. So probably depends on some state.

**Comment by emartineau** [comment] 2019-11-11 13:17
I was able to reproduce this, but only once so far so the cause is still unknown.  

Looking into it.

**Comment by ite-klass** [comment] 2019-11-11 14:12
Last Friday It did happen to me when I was not opening a new file as well. So it is not limited to that. Unfortunately I do not remember what it was I was doing.

I did not identify better reproducibility either yet.

Maybe starting analysis from the code rather then reproducibility would be more reasonable? Maybe there is an obvious null check missing?

**Comment by ite-klass** [comment] 2019-11-11 16:17
It seems to happen a lot more in non standard-dotnet code editors.

I am working with a second instance of VS in a DB project, which makes use of table/sql editor and scmp window. Working with this project seems to trigger it (a lot more than my dotnet VS).

**Comment by ite-klass** [comment] 2019-11-11 16:18
My guess is that the plugin gets notified when there is not actually text/editable text selected (but GUI control stuff) as it expects, and it then fails.

**Comment by emartineau** [comment] 2019-11-12 13:35
The extension currently gets notified whenever there is a change to the `TextBuffer` (the backend object that stores the text data). How that change is determined is out of my control, but right now my code makes the assumption that if the `TextBuffer` changes, there would be a `TextSelection` object associated with it. But perhaps in a non-standard editor this might not be the case (and there may be some race condition with the standard editors too). I just put out a small update that does a null check on the selection. Let me know if that helps things, thanks!

**Comment by emartineau** [comment] 2020-01-12 16:38
Seems the change I mentioned above fixed the issue since no further feedback was given and I've been unable to reproduce this problem after the update. Closing.

**Closed by emartineau** 2020-01-12 16:38 UTC
